name: docker_publish

on:
  push:
    branches:
    - 'hiep/add-github-actions'
    tags:
    - 'hiep/add-github-actions'
  
jobs:
  lint_test:
    uses: babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-lint: true
      integration-tests-require-sudo: true
      
  docker_pipeline:
    uses: babylonchain/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
      publish: true
      dockerfile: ./contrib/images/babylond/Dockerfile