name: docker_publish

on:
  push:
    branches:
    - 'main'
    - 'dev'
    tags:
    - '*'
  
jobs:
  lint_test:
    uses: babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-lint: true
      integration-tests-command: |
        "sudo make test-e2e"
      
  docker_pipeline:
    uses: babylonchain/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-reusable-workflows
    needs: ["lint_test"]
    secrets: inherit
    with:
      publish: true
      dockerfile: ./contrib/images/babylond/Dockerfile
      repoName: babylond